-- Phase 5 (SPEC §18, §20, §21): canonical MIS heads and global library seed (generated from
-- packages/semantic), head classes, and semantic / engine / validation config.

-- The class a mapping must not cross (gross-profit boundary, statement side). ADR 0020.
alter table public.mis_heads add column class text not null default 'memo'
  check (class in ('income', 'direct_cost', 'indirect_cost', 'equity_liability', 'asset', 'memo'));

-- BEGIN GENERATED SEED (packages/semantic seed-sql)
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values (null, 'PL', 'Statement of Profit and Loss', 'pnl', 'Part II', 'debit', 'memo', 1000, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'PL'), 'REV', 'Revenue from operations', 'pnl', 'Part II I', 'credit', 'income', 1010, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'REV'), 'REV_PRODUCTS', 'Sale of products', 'pnl', 'Note: revenue (a)', 'credit', 'income', 1020, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'REV'), 'REV_SERVICES', 'Sale of services', 'pnl', 'Note: revenue (b)', 'credit', 'income', 1030, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'REV'), 'REV_OTHER_OPS', 'Other operating revenue', 'pnl', 'Note: revenue (c)', 'credit', 'income', 1040, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'PL'), 'OTH_INC', 'Other income', 'pnl', 'Part II II', 'credit', 'income', 1050, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OTH_INC'), 'OTH_INC_INTEREST', 'Interest income', 'pnl', null, 'credit', 'income', 1060, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OTH_INC'), 'OTH_INC_OTHER', 'Other non-operating income', 'pnl', null, 'credit', 'income', 1070, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'PL'), 'COGS', 'Direct costs', 'pnl', null, 'debit', 'direct_cost', 1080, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'COGS'), 'COGS_MATERIALS', 'Cost of materials consumed', 'pnl', 'Part II IV (a)', 'debit', 'direct_cost', 1090, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'COGS'), 'COGS_PURCHASES', 'Purchases of stock-in-trade', 'pnl', 'Part II IV (b)', 'debit', 'direct_cost', 1100, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'COGS'), 'COGS_INV_CHANGE', 'Changes in inventories', 'pnl', 'Part II IV (c)', 'debit', 'direct_cost', 1110, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'COGS'), 'COGS_DIRECT', 'Direct expenses', 'pnl', null, 'debit', 'direct_cost', 1120, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'PL'), 'EMP', 'Employee benefits expense', 'pnl', 'Part II IV (d)', 'debit', 'indirect_cost', 1130, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'EMP'), 'EMP_SALARIES', 'Salaries and wages', 'pnl', null, 'debit', 'indirect_cost', 1140, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'EMP'), 'EMP_CONTRIB', 'Contribution to provident and other funds', 'pnl', null, 'debit', 'indirect_cost', 1150, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'EMP'), 'EMP_WELFARE', 'Staff welfare expenses', 'pnl', null, 'debit', 'indirect_cost', 1160, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'PL'), 'OPEX', 'Other expenses', 'pnl', 'Part II IV (f)', 'debit', 'indirect_cost', 1170, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OPEX'), 'OPEX_RENT', 'Rent', 'pnl', null, 'debit', 'indirect_cost', 1180, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OPEX'), 'OPEX_POWER', 'Power and fuel', 'pnl', null, 'debit', 'indirect_cost', 1190, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OPEX'), 'OPEX_REPAIRS', 'Repairs and maintenance', 'pnl', null, 'debit', 'indirect_cost', 1200, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OPEX'), 'OPEX_INSURANCE', 'Insurance', 'pnl', null, 'debit', 'indirect_cost', 1210, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OPEX'), 'OPEX_RATES', 'Rates and taxes', 'pnl', null, 'debit', 'indirect_cost', 1220, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OPEX'), 'OPEX_COMMS', 'Communication', 'pnl', null, 'debit', 'indirect_cost', 1230, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OPEX'), 'OPEX_PRINTING', 'Printing and stationery', 'pnl', null, 'debit', 'indirect_cost', 1240, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OPEX'), 'OPEX_TRAVEL', 'Travelling and conveyance', 'pnl', null, 'debit', 'indirect_cost', 1250, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OPEX'), 'OPEX_PROFESSIONAL', 'Legal and professional fees', 'pnl', null, 'debit', 'indirect_cost', 1260, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OPEX'), 'OPEX_AUDIT', 'Payment to auditors', 'pnl', null, 'debit', 'indirect_cost', 1270, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OPEX'), 'OPEX_MARKETING', 'Advertising and sales promotion', 'pnl', null, 'debit', 'indirect_cost', 1280, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OPEX'), 'OPEX_FREIGHT_OUT', 'Freight outward', 'pnl', null, 'debit', 'indirect_cost', 1290, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OPEX'), 'OPEX_BANK', 'Bank charges', 'pnl', null, 'debit', 'indirect_cost', 1300, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OPEX'), 'OPEX_SOFTWARE', 'Software and subscriptions', 'pnl', null, 'debit', 'indirect_cost', 1310, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OPEX'), 'OPEX_BAD_DEBTS', 'Bad debts written off', 'pnl', null, 'debit', 'indirect_cost', 1320, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'OPEX'), 'OPEX_OTHER', 'Miscellaneous expenses', 'pnl', null, 'debit', 'indirect_cost', 1330, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'PL'), 'DA', 'Depreciation and amortisation expense', 'pnl', 'Part II IV (e)', 'debit', 'indirect_cost', 1340, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'PL'), 'FIN', 'Finance costs', 'pnl', 'Part II IV (c) finance', 'debit', 'indirect_cost', 1350, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'PL'), 'EXC', 'Exceptional items', 'pnl', 'Part II V', 'debit', 'indirect_cost', 1360, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'PL'), 'TAX', 'Tax expense', 'pnl', 'Part II VIII', 'debit', 'indirect_cost', 1370, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'TAX'), 'TAX_CURRENT', 'Current tax', 'pnl', 'Part II VIII (1)', 'debit', 'indirect_cost', 1380, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'TAX'), 'TAX_DEFERRED', 'Deferred tax', 'pnl', 'Part II VIII (2)', 'debit', 'indirect_cost', 1390, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values (null, 'BS', 'Balance Sheet', 'balance_sheet', 'Part I', 'debit', 'memo', 5000, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'BS'), 'EQ', 'Shareholders'' funds', 'balance_sheet', 'Part I I (1)', 'credit', 'equity_liability', 5010, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'EQ'), 'EQ_CAPITAL', 'Share capital / partners'' capital', 'balance_sheet', 'Part I I (1)(a)', 'credit', 'equity_liability', 5020, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'EQ'), 'EQ_RESERVES', 'Reserves and surplus', 'balance_sheet', 'Part I I (1)(b)', 'credit', 'equity_liability', 5030, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'BS'), 'NCL', 'Non-current liabilities', 'balance_sheet', 'Part I I (3)', 'credit', 'equity_liability', 5040, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'NCL'), 'NCL_BORROWINGS', 'Long-term borrowings', 'balance_sheet', 'Part I I (3)(a)', 'credit', 'equity_liability', 5050, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'NCL'), 'NCL_OTHER', 'Other long-term liabilities', 'balance_sheet', 'Part I I (3)(c)', 'credit', 'equity_liability', 5060, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'BS'), 'CL', 'Current liabilities', 'balance_sheet', 'Part I I (4)', 'credit', 'equity_liability', 5070, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'CL'), 'CL_BORROWINGS', 'Short-term borrowings', 'balance_sheet', 'Part I I (4)(a)', 'credit', 'equity_liability', 5080, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'CL'), 'CL_PAYABLES', 'Trade payables', 'balance_sheet', 'Part I I (4)(b)', 'credit', 'equity_liability', 5090, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'CL'), 'CL_STATUTORY', 'Statutory dues', 'balance_sheet', 'Part I I (4)(c)', 'credit', 'equity_liability', 5100, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'CL'), 'CL_OTHER', 'Other current liabilities', 'balance_sheet', 'Part I I (4)(c)', 'credit', 'equity_liability', 5110, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'CL'), 'CL_PROVISIONS', 'Short-term provisions', 'balance_sheet', 'Part I I (4)(d)', 'credit', 'equity_liability', 5120, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'BS'), 'NCA', 'Non-current assets', 'balance_sheet', 'Part I II (1)', 'debit', 'asset', 5130, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'NCA'), 'NCA_PPE', 'Property, plant and equipment', 'balance_sheet', 'Part I II (1)(a)(i)', 'debit', 'asset', 5140, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'NCA'), 'NCA_INTANGIBLES', 'Intangible assets', 'balance_sheet', 'Part I II (1)(a)(ii)', 'debit', 'asset', 5150, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'NCA'), 'NCA_INVESTMENTS', 'Non-current investments', 'balance_sheet', 'Part I II (1)(b)', 'debit', 'asset', 5160, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'NCA'), 'NCA_DEPOSITS', 'Long-term loans, advances and deposits', 'balance_sheet', 'Part I II (1)(d)', 'debit', 'asset', 5170, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'NCA'), 'NCA_OTHER', 'Other non-current assets', 'balance_sheet', 'Part I II (1)(e)', 'debit', 'asset', 5180, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'BS'), 'CA', 'Current assets', 'balance_sheet', 'Part I II (2)', 'debit', 'asset', 5190, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'CA'), 'CA_INVENTORY', 'Inventories', 'balance_sheet', 'Part I II (2)(b)', 'debit', 'asset', 5200, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'CA'), 'CA_RECEIVABLES', 'Trade receivables', 'balance_sheet', 'Part I II (2)(c)', 'debit', 'asset', 5210, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'CA'), 'CA_CASH', 'Cash and bank balances', 'balance_sheet', 'Part I II (2)(d)', 'debit', 'asset', 5220, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'CA'), 'CA_LOANS_ADV', 'Short-term loans and advances', 'balance_sheet', 'Part I II (2)(e)', 'debit', 'asset', 5230, 1) on conflict (code) do nothing;
insert into public.mis_heads (parent_id, code, name, statement, schedule_iii_ref, normal_balance, class, sort_order, version) values ((select id from public.mis_heads where code = 'CA'), 'CA_OTHER', 'Other current assets', 'balance_sheet', 'Part I II (2)(f)', 'debit', 'asset', 5240, 1) on conflict (code) do nothing;
update public.mis_heads set class = 'memo', version = 1 where code = 'UNMAPPED';
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('sales', array['sales account', 'sale of goods', 'domestic sales', 'local sales']::text[], (select id from public.mis_heads where code = 'REV_PRODUCTS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('export sales', array['sales export', 'exports']::text[], (select id from public.mis_heads where code = 'REV_PRODUCTS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('interstate sales', array['inter state sales', 'igst sales']::text[], (select id from public.mis_heads where code = 'REV_PRODUCTS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('service income', array['income from services', 'service charges received', 'consultancy income']::text[], (select id from public.mis_heads where code = 'REV_SERVICES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('job work income', array['job work charges received', 'labour charges received']::text[], (select id from public.mis_heads where code = 'REV_SERVICES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('scrap sales', array['sale of scrap']::text[], (select id from public.mis_heads where code = 'REV_OTHER_OPS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('export incentives', array['duty drawback']::text[], (select id from public.mis_heads where code = 'REV_OTHER_OPS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('sales returns', array['sales return']::text[], (select id from public.mis_heads where code = 'REV_PRODUCTS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('interest received', array['interest income', 'interest on fixed deposit', 'interest on savings', 'interest on deposits']::text[], (select id from public.mis_heads where code = 'OTH_INC_INTEREST'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('discount received', array['discounts received']::text[], (select id from public.mis_heads where code = 'OTH_INC_OTHER'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('dividend received', array['dividend income']::text[], (select id from public.mis_heads where code = 'OTH_INC_OTHER'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('rent received', array['rental income']::text[], (select id from public.mis_heads where code = 'OTH_INC_OTHER'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('profit on sale of fixed assets', array['profit on sale of assets']::text[], (select id from public.mis_heads where code = 'OTH_INC_OTHER'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('foreign exchange gain', array['forex gain', 'exchange gain']::text[], (select id from public.mis_heads where code = 'OTH_INC_OTHER'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('miscellaneous income', array['other income', 'sundry income']::text[], (select id from public.mis_heads where code = 'OTH_INC_OTHER'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('purchases', array['purchase account', 'purchase of goods', 'local purchases']::text[], (select id from public.mis_heads where code = 'COGS_PURCHASES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('import purchases', array['purchase import', 'imports']::text[], (select id from public.mis_heads where code = 'COGS_PURCHASES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('interstate purchases', array['inter state purchases', 'igst purchases']::text[], (select id from public.mis_heads where code = 'COGS_PURCHASES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('purchase returns', array['purchase return']::text[], (select id from public.mis_heads where code = 'COGS_PURCHASES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('raw material consumed', array['raw materials consumed', 'consumption of raw material']::text[], (select id from public.mis_heads where code = 'COGS_MATERIALS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('purchase of raw material', array['raw material purchases']::text[], (select id from public.mis_heads where code = 'COGS_MATERIALS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('packing material', array['packing materials', 'packaging material']::text[], (select id from public.mis_heads where code = 'COGS_MATERIALS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('changes in inventory', array['change in inventory', 'changes in inventories', 'increase decrease in stock']::text[], (select id from public.mis_heads where code = 'COGS_INV_CHANGE'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('opening stock', array[]::text[], (select id from public.mis_heads where code = 'COGS_INV_CHANGE'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('freight inward', array['carriage inward', 'freight inwards', 'cartage inward']::text[], (select id from public.mis_heads where code = 'COGS_DIRECT'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('job work charges', array['job work expenses', 'labour charges']::text[], (select id from public.mis_heads where code = 'COGS_DIRECT'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('manufacturing expenses', array['factory expenses', 'production expenses']::text[], (select id from public.mis_heads where code = 'COGS_DIRECT'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('direct expenses', array[]::text[], (select id from public.mis_heads where code = 'COGS_DIRECT'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('custom duty', array['customs duty', 'import duty']::text[], (select id from public.mis_heads where code = 'COGS_DIRECT'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('factory wages', array['direct wages', 'direct labour']::text[], (select id from public.mis_heads where code = 'COGS_DIRECT'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('salary', array['salary and wages', 'salary account', 'staff salary', 'salary to staff', 'wages', 'salary and allowances']::text[], (select id from public.mis_heads where code = 'EMP_SALARIES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('employee costs', array['employee benefits expenses', 'employee benefit expenses', 'staff costs', 'personnel costs']::text[], (select id from public.mis_heads where code = 'EMP_SALARIES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('bonus', array['bonus to staff', 'incentives to staff']::text[], (select id from public.mis_heads where code = 'EMP_SALARIES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('directors remuneration', array['partners remuneration', 'remuneration to partners', 'remuneration to directors']::text[], (select id from public.mis_heads where code = 'EMP_SALARIES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('gratuity', array['leave encashment']::text[], (select id from public.mis_heads where code = 'EMP_SALARIES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('employer contribution to provident fund', array['contribution to provident fund', 'provident fund contribution', 'employer provident fund']::text[], (select id from public.mis_heads where code = 'EMP_CONTRIB'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('employer contribution to esic', array['contribution to esic', 'esic contribution', 'employer esic']::text[], (select id from public.mis_heads where code = 'EMP_CONTRIB'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('staff welfare', array['staff welfare expenses', 'employee welfare']::text[], (select id from public.mis_heads where code = 'EMP_WELFARE'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('rent', array['office rent', 'rent paid', 'rent account', 'warehouse rent', 'godown rent']::text[], (select id from public.mis_heads where code = 'OPEX_RENT'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('electricity', array['electricity charges', 'electricity expenses', 'power and fuel', 'power charges']::text[], (select id from public.mis_heads where code = 'OPEX_POWER'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('repairs and maintenance', array['repairs', 'maintenance', 'repair and maintenance']::text[], (select id from public.mis_heads where code = 'OPEX_REPAIRS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('insurance', array['insurance expenses', 'insurance premium']::text[], (select id from public.mis_heads where code = 'OPEX_INSURANCE'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('rates and taxes', array['municipal taxes', 'property tax']::text[], (select id from public.mis_heads where code = 'OPEX_RATES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('telephone', array['telephone and internet', 'telephone expenses', 'internet charges', 'mobile expenses', 'communication expenses']::text[], (select id from public.mis_heads where code = 'OPEX_COMMS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('printing and stationery', array['stationery', 'printing and stationary']::text[], (select id from public.mis_heads where code = 'OPEX_PRINTING'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('travelling expenses', array['travel expenses', 'travelling and conveyance', 'conveyance', 'conveyance expenses', 'local conveyance']::text[], (select id from public.mis_heads where code = 'OPEX_TRAVEL'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('legal and professional fees', array['professional fees', 'legal fees', 'consultancy charges', 'professional charges']::text[], (select id from public.mis_heads where code = 'OPEX_PROFESSIONAL'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('audit fees', array['auditors remuneration', 'payment to auditors', 'statutory audit fees']::text[], (select id from public.mis_heads where code = 'OPEX_AUDIT'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('advertisement', array['advertising', 'advertisement expenses', 'sales promotion', 'business promotion', 'marketing expenses']::text[], (select id from public.mis_heads where code = 'OPEX_MARKETING'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('freight outward', array['carriage outward', 'freight outwards', 'delivery charges']::text[], (select id from public.mis_heads where code = 'OPEX_FREIGHT_OUT'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('bank charges', array['bank charges and commission', 'bank commission']::text[], (select id from public.mis_heads where code = 'OPEX_BANK'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('software subscriptions', array['software expenses', 'subscription charges']::text[], (select id from public.mis_heads where code = 'OPEX_SOFTWARE'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('bad debts', array['bad debts written off', 'sundry balances written off']::text[], (select id from public.mis_heads where code = 'OPEX_BAD_DEBTS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('office expenses', array['general expenses', 'sundry expenses', 'miscellaneous expenses', 'administrative expenses']::text[], (select id from public.mis_heads where code = 'OPEX_OTHER'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('commission paid', array['brokerage paid', 'commission']::text[], (select id from public.mis_heads where code = 'OPEX_OTHER'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('donation', array['donations']::text[], (select id from public.mis_heads where code = 'OPEX_OTHER'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('round off', array['rounding off', 'round off account']::text[], (select id from public.mis_heads where code = 'OPEX_OTHER'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('loss on sale of fixed assets', array['loss on sale of assets']::text[], (select id from public.mis_heads where code = 'OPEX_OTHER'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('foreign exchange loss', array['forex loss', 'exchange loss']::text[], (select id from public.mis_heads where code = 'OPEX_OTHER'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('depreciation', array['depreciation account', 'depreciation on fixed assets', 'depreciation and amortisation']::text[], (select id from public.mis_heads where code = 'DA'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('amortisation', array['amortisation of intangibles']::text[], (select id from public.mis_heads where code = 'DA'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('interest paid', array['interest expenses', 'interest on loan', 'interest on term loan', 'interest on overdraft', 'interest on cash credit', 'bank interest']::text[], (select id from public.mis_heads where code = 'FIN'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('loan processing charges', array['processing fees on loan']::text[], (select id from public.mis_heads where code = 'FIN'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('income tax', array['provision for income tax', 'current tax', 'income tax expenses']::text[], (select id from public.mis_heads where code = 'TAX_CURRENT'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('deferred tax', array['deferred tax expenses']::text[], (select id from public.mis_heads where code = 'TAX_DEFERRED'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('capital account', array['capital', 'share capital', 'partners capital', 'proprietors capital', 'equity share capital']::text[], (select id from public.mis_heads where code = 'EQ_CAPITAL'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('reserves and surplus', array['general reserve', 'retained earnings', 'securities premium']::text[], (select id from public.mis_heads where code = 'EQ_RESERVES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('profit and loss account', array['surplus in profit and loss']::text[], (select id from public.mis_heads where code = 'EQ_RESERVES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('drawings', array['partners drawings', 'proprietors drawings']::text[], (select id from public.mis_heads where code = 'EQ_CAPITAL'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('term loan', array['secured loan', 'vehicle loan', 'long term loan']::text[], (select id from public.mis_heads where code = 'NCL_BORROWINGS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('unsecured loans', array['loan from directors', 'loan from partners', 'loan from partner', 'loans from related parties']::text[], (select id from public.mis_heads where code = 'NCL_BORROWINGS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('bank overdraft', array['overdraft', 'cash credit', 'bank cash credit', 'working capital loan']::text[], (select id from public.mis_heads where code = 'CL_BORROWINGS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('sundry creditors', array['trade payables', 'creditors']::text[], (select id from public.mis_heads where code = 'CL_PAYABLES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('output cgst', array['cgst payable']::text[], (select id from public.mis_heads where code = 'CL_STATUTORY'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('output sgst', array['sgst payable']::text[], (select id from public.mis_heads where code = 'CL_STATUTORY'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('output igst', array['igst payable']::text[], (select id from public.mis_heads where code = 'CL_STATUTORY'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('input cgst', array[]::text[], (select id from public.mis_heads where code = 'CL_STATUTORY'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('input sgst', array[]::text[], (select id from public.mis_heads where code = 'CL_STATUTORY'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('input igst', array[]::text[], (select id from public.mis_heads where code = 'CL_STATUTORY'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('tds payable', array['tds on salary', 'tds on contract', 'tds on professional fees', 'tds on rent']::text[], (select id from public.mis_heads where code = 'CL_STATUTORY'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('gst payable', array['gst liability']::text[], (select id from public.mis_heads where code = 'CL_STATUTORY'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('provident fund payable', array[]::text[], (select id from public.mis_heads where code = 'CL_STATUTORY'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('esic payable', array[]::text[], (select id from public.mis_heads where code = 'CL_STATUTORY'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('professional tax payable', array['pt payable']::text[], (select id from public.mis_heads where code = 'CL_STATUTORY'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('salary payable', array['wages payable', 'outstanding salary']::text[], (select id from public.mis_heads where code = 'CL_PROVISIONS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('provision for expenses', array['outstanding expenses', 'expenses payable']::text[], (select id from public.mis_heads where code = 'CL_PROVISIONS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('advance from customers', array['customer advances']::text[], (select id from public.mis_heads where code = 'CL_OTHER'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('fixed assets', array['plant and machinery', 'furniture and fixtures', 'computers', 'office equipment', 'vehicles', 'building', 'land', 'delivery vehicle', 'motor car']::text[], (select id from public.mis_heads where code = 'NCA_PPE'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('accumulated depreciation', array['provision for depreciation']::text[], (select id from public.mis_heads where code = 'NCA_PPE'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('intangible assets', array['software', 'goodwill', 'trademark']::text[], (select id from public.mis_heads where code = 'NCA_INTANGIBLES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('investments', array['fixed deposit', 'mutual funds', 'shares']::text[], (select id from public.mis_heads where code = 'NCA_INVESTMENTS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('security deposit', array['security deposits', 'rent deposit', 'electricity deposit']::text[], (select id from public.mis_heads where code = 'NCA_DEPOSITS'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('closing stock', array['stock in hand', 'inventory', 'stock']::text[], (select id from public.mis_heads where code = 'CA_INVENTORY'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('sundry debtors', array['trade receivables', 'debtors']::text[], (select id from public.mis_heads where code = 'CA_RECEIVABLES'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('cash', array['cash in hand', 'petty cash', 'cash account']::text[], (select id from public.mis_heads where code = 'CA_CASH'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('bank account', array['current account', 'savings account', 'bank']::text[], (select id from public.mis_heads where code = 'CA_CASH'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('advance to suppliers', array['supplier advances', 'advance to creditors']::text[], (select id from public.mis_heads where code = 'CA_LOANS_ADV'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('staff advance', array['advance to staff', 'salary advance', 'loans to employees']::text[], (select id from public.mis_heads where code = 'CA_LOANS_ADV'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('tds receivable', array['tds receivables', 'advance tax', 'tax deducted at source']::text[], (select id from public.mis_heads where code = 'CA_LOANS_ADV'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('gst input credit', array['input tax credit', 'gst receivable']::text[], (select id from public.mis_heads where code = 'CA_OTHER'), 'seed') on conflict (normalized_name) do nothing;
insert into public.global_mapping_library (normalized_name, aliases, mis_head_id, source) values ('prepaid expenses', array['prepaid insurance']::text[], (select id from public.mis_heads where code = 'CA_OTHER'), 'seed') on conflict (normalized_name) do nothing;
-- END GENERATED SEED

insert into public.app_config (key, value) values
  -- SPEC §18 step 4: fuzzy library matches at or above this Dice similarity are proposed for review.
  ('semantic.fuzzy_threshold', '"0.85"'::jsonb),
  -- SPEC §18: a library candidate needs this many distinct accounts (admin-reviewed, Phase 9).
  ('semantic.library_promotion_min_accounts', '5'::jsonb),
  -- SPEC §21 V3: trial balance debit/credit tolerance in paise.
  ('validation.tb_tolerance_paise', '0'::jsonb),
  -- SPEC §21 V5/V6: balance sheet and profit reconciliation tolerance in paise.
  ('validation.reconciliation_tolerance_paise', '0'::jsonb),
  -- SPEC §20: ageing buckets in days from bill date; the last bucket is open-ended.
  ('engine.ageing_buckets', '[[0, 30], [31, 60], [61, 90], [91, 180], [181, null]]'::jsonb),
  -- SPEC §21 V10: heads whose balance direction is checked, with the expected sign.
  ('validation.sign_sanity_heads', '["REV", "COGS", "EMP", "OPEX", "DA", "FIN", "CA_CASH", "CA_INVENTORY", "CL_PAYABLES", "CA_RECEIVABLES"]'::jsonb)
on conflict (key, version) do nothing;
