/**
 * Maintained abbreviation list for ledger-name matching (SPEC §18). Keys are single normalised
 * tokens (lowercase, punctuation already stripped, so "a/c" arrives as "ac").
 * Expansions must themselves be normalised text.
 */

export const ABBREVIATIONS: Readonly<Record<string, string>> = {
  ac: "account",
  acc: "account",
  acct: "account",
  accts: "accounts",
  adv: "advance",
  advs: "advances",
  allow: "allowance",
  amort: "amortisation",
  amortization: "amortisation",
  bal: "balance",
  bldg: "building",
  chgs: "charges",
  chrgs: "charges",
  comm: "commission",
  conv: "conveyance",
  dep: "depreciation",
  depn: "depreciation",
  depr: "depreciation",
  elec: "electricity",
  emp: "employee",
  esi: "esic",
  exp: "expenses",
  expd: "expenses",
  exps: "expenses",
  expense: "expenses",
  fd: "fixed deposit",
  furn: "furniture",
  govt: "government",
  ins: "insurance",
  int: "interest",
  inv: "inventory",
  ltd: "limited",
  maint: "maintenance",
  mgmt: "management",
  misc: "miscellaneous",
  od: "overdraft",
  pl: "profit and loss",
  pf: "provident fund",
  pmt: "payment",
  prof: "professional",
  prov: "provision",
  pvt: "private",
  pymt: "payment",
  rcvd: "received",
  recd: "received",
  rem: "remuneration",
  sal: "salary",
  salaries: "salary",
  stat: "statutory",
  tel: "telephone",
  trf: "transfer",
  veh: "vehicle",
  wc: "working capital",
};
